---
title: "WarsawStockExchangeAnalysis"
output: html_notebook
---

```{r}
# Wczytanie niezbędnych pakietów
require(tidyverse)

# Wczytanie i uporządkowanie danych
read_data <- function(csv_file) {
  data <- read_csv(csv_file) %>% 
    mutate(Year = year(Data)) %>% 
    select(Year, Open = Otwarcie, Close = Zamkniecie) %>%
    arrange(Year)
}

wig_df <- read_data("wig_y.csv")
fund1429_df <- read_data("1429_n_y.csv")
fund1655_df <- read_data("1655_n_y.csv")
fund2162_df <- read_data("2162_n_y.csv")
```

```{r}
# Funkcja do obliczenia rocznych stóp zwrotu
calculate_annual_returns <- function(df) {
  df %>%
    mutate(ReturnRate = (Close / Open) - 1, ReturnLogRate = log(Close / Open)) %>%
    select(Year, ReturnRate, ReturnLogRate)
}

# Obliczenie stóp zwrotu dla wskaźnika WIG oraz funduszy inwestycyjnych
wig_ar_df <- calculate_annual_returns(wig_df)
fund1429_ar_df <- calculate_annual_returns(fund1429_df)
fund1655_ar_df <- calculate_annual_returns(fund1655_df)
fund2162_ar_df <- calculate_annual_returns(fund2162_df)
```

```{r}
# Funkcja do wyliczania statystyk w danym okresie dla podanego wskaźnika bądź funduszu
get_stats_for_period <- function(instrument, ar_df, years) {
  # Maksymalny dostępny rok
  max_year <- max(ar_df$Year)

  # Wybranie ostatnich 'n' lat
  selected_df <- ar_df %>%
    filter(Year > (max_year - years))

  # Obliczenie statystyk
  cumulative_rr <- exp(sum(selected_df$ReturnLogRate, na.rm = TRUE)) - 1
  # TODO: Tutaj mam dylemat czy brac te logarytmiczna czy zwykla, generalnie na wykresach wyglądaja podobnie
  rr_mean <- mean(selected_df$ReturnLogRate, na.rm = TRUE)
  rr_sd <- sd(selected_df$ReturnLogRate, na.rm = TRUE)
  # Współczynnik zmienności
  cv <- rr_sd / rr_mean
  
  # Zwracanie jako tibble
  tibble(
    Instrument = instrument,
    Years = as.factor(years),
    CumulativeReturnRate = round(cumulative_rr, 4),
    AnnualReturnRateAvg = round(rr_mean, 4),
    AnnualReturnRateSd = round(rr_sd, 4),
    CoefficientOfVariation = round(cv, 4)
  )
}

periods <- c(3, 5, 10)
instruments <- c("WIG", "1429.N", "1655.N", "2162.N")
wig_stats_df <- map_dfr(periods, ~get_stats_for_period(instruments[1], wig_ar_df, .x))
fund1429_stats_df <- map_dfr(periods, ~get_stats_for_period(instruments[2], fund1429_ar_df, .x))
fund1655_stats_df <- map_dfr(periods, ~get_stats_for_period(instruments[3], fund1655_ar_df, .x))
fund2162_stats_df <- map_dfr(periods, ~get_stats_for_period(instruments[4], fund2162_ar_df, .x))

all_instruments_stats_df <- bind_rows(wig_stats_df, fund1429_stats_df, fund1655_stats_df, fund2162_stats_df)
all_instruments_stats_df <- all_instruments_stats_df %>%
  mutate(Instrument = factor(Instrument, levels = instruments))
```

```{r}
# Funkcja do wizualizacji wykresu, gdzie dla 3 okresów pokazujemy, jak się zmieniały dane statystyki dla dostarczonych instrumentów finansowych
visualize_all_instruments_stats_chart <- function(y_param, title, y_lab) {
  ggplot(all_instruments_stats_df, aes(x = Instrument, y = y_param, fill = Years)) +
    geom_col(position = "dodge") +
    labs(
      title = title,
      x = NULL,
      y = y_lab,
      fill = "Okres inwestycji"
    ) +
    scale_fill_manual(
      values = c(
        "3" = "#2E75B6",
        "5" = "#C55A11",
        "10" = "#A5A5A5"
      ),
      labels = c("3 lata", "5 lat", "10 lat")
    ) +
    theme_light() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5))
}
```

```{r}
visualize_all_instruments_stats_chart(all_instruments_stats_df$CumulativeReturnRate, "Skumulowana stopa zwrotu za dany okres", "Skumulowana stopa zwrotu")
```

```{r}
visualize_all_instruments_stats_chart(all_instruments_stats_df$AnnualReturnRateAvg, "Średnia roczna stopa zwrotu za dany okres", "Średnia roczna stopa zwrotu")
```

```{r}
visualize_all_instruments_stats_chart(all_instruments_stats_df$AnnualReturnRateSd, "Odchylenie standardowe rocznej stopy zwrotu za dany okres", "Odchylenie standardowe")
```

```{r}
# Funkcja do wizualizacji wykresu, gdzie pokazujemy zależność stopa zwrotu - odchylenie standardowe w konkretnym okresie dla dostarczonych instrumentów finansowych
visualize_all_instruments_rr_sd_chart <- function(period) {
  all_instruments_period_stats_df <- all_instruments_stats_df %>%
    filter(Years == period)
    ggplot(all_instruments_period_stats_df, aes(x = CumulativeReturnRate, y = AnnualReturnRateSd, label = Instrument)) + 
    geom_point(size = 3, color = "#2E75B6") +
    geom_text(vjust = -0.8, size = 4) +
    labs(
      title = paste("Zysk vs ryzyko – okres", period, "lat"),
      x = "Skumulowana stopa zwrotu",
      y = "Odchylenie standardowe"
      ) +
    scale_x_continuous(expand = expansion(mult = c(0.1, 0.1))) +
    scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) +
    theme_light() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5))
}
```

```{r}
visualize_all_instruments_rr_sd_chart(periods[1])
```

```{r}
visualize_all_instruments_rr_sd_chart(periods[2])
```

```{r}
visualize_all_instruments_rr_sd_chart(periods[3])
```

```{r}
# Funkcja do wizualizacji wykresu, gdzie pokazujemy zależność odchylenie standardowe - współczynnik zmienności w konkretnym okresie dla dostarczonych instrumentów finansowych
visualize_all_instruments_sd_cv_chart <- function(period) {
  all_instruments_period_stats_df <- all_instruments_stats_df %>%
    filter(Years == period)
    ggplot(all_instruments_period_stats_df, aes(x = AnnualReturnRateSd, y = CoefficientOfVariation, label = Instrument)) + 
    geom_point(size = 3, color = "#2E75B6") +
    geom_text(vjust = -0.8, size = 4) +
    labs(
      title = paste("Współczynnik zmienności – okres", period, "lat"),
      x = "Odchylenie standardowe",
      y = "Współczynnik zmienności"
      ) +
    scale_x_continuous(expand = expansion(mult = c(0.1, 0.1))) +
    scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) +
    theme_light() +
    theme(plot.title = element_text(face = "bold", hjust = 0.5))
}
```

```{r}
visualize_all_instruments_sd_cv_chart(periods[1])
```

```{r}
visualize_all_instruments_sd_cv_chart(periods[2])
```

```{r}
visualize_all_instruments_sd_cv_chart(periods[3])
```